spring.application.name=notification-service
server.port=8088

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
