spring.application.name=consulta-service
server.port=${SERVER_PORT:8087}

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

apiperu.token=${APIPERU_TOKEN:39d6e476c19a3b8a566bc88591ecbcc3f6cda5c763d4216ef0ef8d1031a1f787}
apiperu.base-url=https://apiperu.dev/api

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
